package model.adfbc.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 04 15:39:40 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewObjViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewObjViewImpl() {
    }
}

